GET http://localhost:5500/profile
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJzdWIiOjEsImlhdCI6MTcyNTY1MjgzMiwiZXhwIjoxNzI1NjUyODkyfQ.vqbY7f-lYtAb5924HKghEqC46XCqHsoMthcgbIdm4k4